---
version: '3'

services:
  mariadb:
    build:
      context: .
      dockerfile: Dockerfile.mariadb
    container_name: db-mariadb
    restart: unless-stopped
    networks:
      - db
    volumes:
      - /data/mariadb_db-mariadb/_data:/var/lib/mysql:rw
      - ./scripts/ssmtp.conf:/etc/ssmtp/ssmtp.conf
      #- db-mariadb:/var/lib/mysql:rw
    ports:
      - "3306:3306"
    env_file: /root/projects/Rabbitmq-Grafana/docker/credentials.env
    command: 'mariadbd --innodb-flush-method=fsync'

  backup:
    build:
      context: .
      dockerfile: Dockerfile.backup
    container_name: mariadb-backup
    restart: unless-stopped
    networks:
      - db
    volumes:
      - /data/mariadb_db-mariadb/_data:/data
      - ./scripts/ssmtp.conf:/etc/ssmtp/ssmtp.conf
    env_file: /root/projects/Rabbitmq-Grafana/docker/credentials.env
    command: >
      sh -c "echo '0 0 * * * /usr/local/bin/mariadb_backup.sh >> /var/log/mariadb_backup.log 2>&1' | crontab - && cron -f"

networks:
  db:

#volumes:
#  db-mariadb:
