[agent]
    interval = "1s"
    round_interval = true
    metric_batch_size = 1000
    metric_buffer_limit = 10000
    collection_jitter = "0s"
    flush_interval = "1s"
    flush_jitter = "0s"
    precision = ""
    debug = true
    quiet = false
    hostname = ""
    omit_hostname = true

## INPUT PLUGINS

# Collect RabbitMQ Metrics
[[inputs.rabbitmq]]

    url = "http://rabbitmq:15672"
    username = "${TELEGRAF_AMQP_BROKER_USERNAME}"
    password = "${TELEGRAF_AMQP_BROKER_PASSWORD}"

    #username = "telegraf"
    #password = "rabbITMQ_Prototype_Stack"

# MQTT => AMQP Bridging
[[inputs.amqp_consumer]]

  ## Brokers to consume from.
  brokers = ["amqp://rabbitmq:5672/"]

  # Authentication credentials for the PLAIN auth_method.
  username = "${TELEGRAF_AMQP_BROKER_USERNAME}"
  password = "${TELEGRAF_AMQP_BROKER_PASSWORD}"

  #username = "telegraf"
  #password = "rabbITMQ_Prototype_Stack"

  ## Name of the exchange to declare.  If unset, no exchange will be declared.
  exchange = "amq.topic"
  ## Exchange type; common types are "direct", "fanout", "topic", "header", "x-consistent-hash".
  exchange_type = "topic"


  ## Exchange durability can be either "transient" or "durable".
  exchange_durability = "durable"

  ## AMQP queue name
  queue = ""

  ## AMQP queue durability can be "transient" or "durable".
  queue_durability = "durable"

  ## If true, queue will be passively declared.
  # queue_passive = false

  ## A binding between the exchange and queue using this binding key is
  ## created.  If unset, no binding is created.


  ## ADAPT CONFIGURATION BELOW ACCORDINGLY

  binding_key = "IOT.#"
  
  ## Data format to consume.
  data_format = "json"

  ## If Payload is JSON use
  # data_format = "json"

  ## Refer to Telegraf documentation on how to Parse incoming JSON


## NOTE: add additional [[inputs.amqp_consumer]] table if
## you have additional services that produce AMQP messages
## and need to be consumed into InfluxDB

## OUTPUT PLUGINS
[[outputs.influxdb_v2]]
  ## The URLs of the InfluxDB cluster nodes.
  ##
  ## Multiple URLs can be specified for a single cluster, only ONE of the
  ## urls will be written to each interval.
  ##   ex: urls = ["https://us-west-2-1.aws.cloud2.influxdata.com"]
  urls = ["http://influxdb:8086"]

  ## Token for authentication.
  token = "${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}"

  ## Organization is the name of the organization you wish to write to.
  organization = "${DOCKER_INFLUXDB_INIT_ORG}"

  ## Destination bucket to write into.
  bucket = "${DOCKER_INFLUXDB_INIT_BUCKET}"

  ## The value of this tag will be used to determine the bucket.  If this
  ## tag is not set the 'bucket' option is used as the default.
  # bucket_tag = ""

  ## If true, the bucket tag will not be added to the metric.
  # exclude_bucket_tag = false

  ## Timeout for HTTP messages.
  # timeout = "5s"
  
  ## HTTP User-Agent
  user_agent = "telegraf"
