{
 "title": "MAINDASHBOARD",
 "description": "MAINDASHBOARD",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "System_Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU_Usage(%)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "queryExecutor",
     "query": "from(bucket: \"system_metrics\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"cpu\" and r._field == \"usage_idle\" and r.cpu == \"cpu-total\")\r\n  |> map(fn: (r) => ({ r with host: \"CPU\" }))\r\n  |> map(fn: (r) => ({ r with _value: 100.0 - r._value }))\r\n  |> keep(columns: [\"_time\", \"_value\", \"host\"])\r\n",
     "select": [
      [
       { "params": [ "queriesActive" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "stats-node-0.infra.ramcloud.io" }
     ]
    }
   ]
  },
  {
   "title": "Memory_Used(%)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "queryExecutor",
     "query": "from(bucket: \"system_metrics\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"mem\" and r._field == \"used_percent\")\r\n  |> map(fn: (r) => ({ r with host: \"Memory\" }))\r\n  |> keep(columns: [\"_time\", \"_value\", \"host\"])\r\n  |> aggregateWindow(every: 5s, fn: mean, createEmpty: false) \r\n",
     "select": [
      [
       { "params": [ "queriesActive" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "stats-node-0.infra.ramcloud.io" }
     ]
    }
   ]
  },
  {
   "title": "Memory_Useable",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "queryExecutor",
     "query": "from(bucket: \"system_metrics\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"mem\" and r._field == \"available\")\r\n  |> map(fn: (r) => ({ r with host: \"Memory\" }))\r\n  |> keep(columns: [\"_time\", \"_value\", \"host\"])\r\n  |> aggregateWindow(every: 5s, fn: mean, createEmpty: false) \r\n",
     "select": [
      [
       { "params": [ "queriesActive" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "stats-node-0.infra.ramcloud.io" }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "used_percent = from(bucket: \"system_metrics\")\r\n  |> range(start: -10m)\r\n  |> filter(fn: (r) => r._measurement == \"disk\" and r._field == \"used_percent\")\r\n  |> map(fn: (r) => ({ r with display_name: r.path }))\r\n  |> rename(columns: { _value: \"Disk Usage (%)\" })  // \"used_percent\"를 \"Disk Usage (%)\"로 변경\r\n\r\ntotal_capacity = from(bucket: \"system_metrics\")\r\n  |> range(start: -10m)\r\n  |> filter(fn: (r) => r._measurement == \"disk\" and r._field == \"total\")\r\n  |> map(fn: (r) => ({ r with display_name: r.path, _value: float(v: r._value) / (1024.0 * 1024.0 * 1024.0) }))\r\n  |> rename(columns: { _value: \"Total Disk Capacity (GB)\" })  // \"total_capacity\"를 \"Total Disk Capacity (GB)\"로 변경\r\n\r\njoin(\r\n    tables: {used_percent: used_percent, total_capacity: total_capacity},\r\n    on: [\"_time\", \"display_name\"]\r\n  )\r\n  |> keep(columns: [\"_time\", \"display_name\", \"Disk Usage (%)\", \"Total Disk Capacity (GB)\"])  // 변경된 필드 이름 유지\r\n"
    }
   ]
  },
  {
   "title": "RabbitMQ Message Count",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "queryExecutor",
     "query": "from(bucket: \"mybucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor_data\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\" or r[\"_field\"] == \"temperature\")\r\n  |> drop(columns: [\"_start\", \"_stop\"])  // 시간 태그 제거\r\n  |> aggregateWindow(every: v.windowPeriod, fn: count, createEmpty: false)  // 메시지 수 계산\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> sort(columns: [\"_time\"], desc: true)\r\n  |> yield(name: \"count\")\r\n",
     "select": [
      [
       { "params": [ "queryDurationNs" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Data_input",
   "type": "table",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor_data\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\" or r[\"_field\"] == \"temperature\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")  // 필드를 열로 변환\r\n  |> sort(columns: [\"_time\"], desc: true)  // 최신순 정렬\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "Data_Input_InfluxDB",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 16, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "influx-0 $col",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "runtime",
     "query": "from(bucket: \"mybucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor_data\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\" or r[\"_field\"] == \"temperature\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "HeapInUse" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "heap active" ], "type": "alias" }
      ],
      [
       { "params": [ "HeapIdle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "heap idle" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "stats-node-0.infra.ramcloud.io" }
     ]
    }
   ]
  },
  { "title": "Mariadb", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Data_input (최신10개)",
   "type": "table",
   "gridPos": { "h": 14, "w": 9, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Data_Input_InfluxDB",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 15, "x": 9, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {}
   ]
  }
 ]
}